// SPDX-License-Identifier: GPL-2.0-or-later
// ─────────────────────────────────────────────────────────────────
// keymap.c — Vial default keymap
// Generated by QMK/Vial Wizard v5.6 on 2026-09-27
// ─────────────────────────────────────────────────────────────────
//
// This is a starting point — a basic QWERTY layout.
// You should remap keys using the Vial GUI after flashing.
// Vial stores your remapped layout in the keyboard's EEPROM,
// so you only need to reflash when changing features, not keycodes.
//
// HOW LAYERS WORK:
// Layer 0 is always active (base layer). Higher-numbered layers
// override lower ones when activated by a layer-switch key (MO, TG, etc).
// KC_TRNS on an upper layer means "fall through to the layer below".
// KC_NO on any layer means "do nothing / no keypress".
//
// MATRIX DIMENSIONS: 6 rows × 20 cols
// (Single board: 6 rows)
//
#include QMK_KEYBOARD_H



const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // ── Layer 0: Base (QWERTY starting point) ────────────────────
    // Edit these keycodes directly, or use Vial to remap via GUI.
    [0] = LAYOUT(
        // row 0
        KC_ESCAPE, KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_PRINT_SCREEN, KC_SCROLL_LOCK, KC_PAUSE, KC_KP_MINUS, KC_KP_PLUS, KC_KP_ENTER,
        // row 1
        KC_GRAVE, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINUS, KC_EQUAL, KC_BACKSPACE, KC_INSERT, KC_HOME, KC_PAGE_UP, KC_NUM_LOCK, KC_KP_SLASH, KC_KP_ASTERISK,
        // row 2
        KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LEFT_BRACKET, KC_RIGHT_BRACKET, KC_BACKSLASH, KC_DELETE, KC_END, KC_PAGE_DOWN, KC_KP_7, KC_KP_8, KC_KP_9,
        // row 3
        KC_CAPS_LOCK, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SEMICOLON, KC_QUOTE, KC_NO, KC_ENTER, KC_NO, KC_NO, KC_NO, KC_KP_4, KC_KP_5, KC_KP_6,
        // row 4
        KC_LEFT_SHIFT, LCTL(KC_P), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMMA, KC_DOT, KC_SLASH, TG(2), KC_RIGHT_SHIFT, KC_NO, KC_UP, KC_NO, KC_KP_1, KC_KP_2, KC_KP_3,
        // row 5
        KC_LEFT_CTRL, KC_LEFT_GUI, KC_LEFT_ALT, MO(1), KC_SPACE, LCTL(KC_A), KC_RIGHT_ALT, MO(1), KC_RIGHT_GUI, KC_RIGHT_CTRL, LCTL(KC_C), LCTL(KC_V), LCTL(KC_X), KC_NO, KC_NO, KC_KP_DOT, KC_LEFT, KC_DOWN, KC_RIGHT, KC_KP_0
    ),

    [1] = LAYOUT(
         // row 0
         KC_NO, KC_NO, KC_AUDIO_MUTE, KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP, KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE, KC_MEDIA_NEXT_TRACK, KC_BRIGHTNESS_DOWN, KC_BRIGHTNESS_UP, LGUI(KC_TAB), LGUI(KC_D), KC_WWW_SEARCH, KC_WWW_HOME, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
         // row 1
         KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BACKLIGHT_TOGGLE_BREATHING, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
         // row 2
         KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BACKLIGHT_TOGGLE, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
         // row 3
         KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
         // row 4
         KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, LGUI(KC_L), KC_NO, KC_NO, QK_BACKLIGHT_UP, KC_NO, KC_NO, KC_NO, KC_NO,
         // row 5
         KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BACKLIGHT_DOWN, KC_NO, KC_NO
    ),

    [2] = LAYOUT(
         // row 0
         KC_NO, KC_NO, KC_AUDIO_MUTE, KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP, KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE, KC_MEDIA_NEXT_TRACK, KC_BRIGHTNESS_DOWN, KC_BRIGHTNESS_UP, LGUI(KC_TAB), LGUI(KC_D), KC_WWW_SEARCH, KC_WWW_HOME, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
         // row 1
         KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BACKLIGHT_TOGGLE_BREATHING, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
         // row 2
         KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BACKLIGHT_TOGGLE, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
         // row 3
         KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
         // row 4
         KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TG(2), KC_NO, KC_NO, QK_BACKLIGHT_UP, KC_NO, KC_NO, KC_NO, KC_NO,
         // row 5
         KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BACKLIGHT_DOWN, KC_NO, KC_NO
    )
};

// ==========================================
// БЛОК УПРАВЛЕНИЯ ИНДИКАТОРАМИ (ACTIVE LOW)
// ==========================================

// 1. Привязка физических пинов контроллера
#define CAPS_LED_PIN  26
#define NUM_LED_PIN   27
#define SCRLK_LED_PIN 28

// 2. Первоначальная настройка пинов при включении USB
void keyboard_pre_init_user(void) {
    setPinOutput(CAPS_LED_PIN);
    setPinOutput(NUM_LED_PIN);
    setPinOutput(SCRLK_LED_PIN);

    // Подаем HIGH, чтобы диоды гарантированно были выключены при старте
    writePinHigh(CAPS_LED_PIN);
    writePinHigh(NUM_LED_PIN);
    writePinHigh(SCRLK_LED_PIN);
}

// 3. СОВРЕМЕННЫЙ вариант отслеживания локов для актуальных версий QMK/Vial
bool led_update_user(led_t led_state) {
    // Управление Caps Lock
    if (led_state.caps_lock) {
        writePinLow(CAPS_LED_PIN);  // ВКЛ -> Прижимаем к земле (диод горит)
    } else {
        writePinHigh(CAPS_LED_PIN); // ВЫКЛ -> Подаем плюс (диод гаснет)
    }

    // Управление Num Lock
    if (led_state.num_lock) {
        writePinLow(NUM_LED_PIN);   // ВКЛ -> Прижимаем к земле (диод горит)
    } else {
        writePinHigh(NUM_LED_PIN);  // ВЫКЛ -> Подаем плюс (диод гаснет)
    }

    // Управление Scroll Lock
    if (led_state.scroll_lock) {
        writePinLow(SCRLK_LED_PIN);  // ВКЛ -> Прижимаем к земле (диод горит)
    } else {
        writePinHigh(SCRLK_LED_PIN); // ВЫКЛ -> Подаем плюс (диод гаснет)
    }

    return true; // Обязательно возвращаем true, чтобы QMK знал, что мы успешно обработали состояние
}

